# Generated by Django 2.2 on 2023-07-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyinfo',
            name='story_img',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/4545/4545027.png', max_length=500),
        ),
    ]
