# Generated by Django 2.2 on 2023-07-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_rave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eggs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=50)),
                ('maleName', models.CharField(max_length=50)),
                ('eggItem', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('hairstyle', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('yesOrNo', models.CharField(max_length=50)),
            ],
        ),
    ]
