# Generated by Django 2.2 on 2023-07-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_eggs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=50)),
                ('bodyPart', models.CharField(max_length=50)),
                ('adjective1', models.CharField(max_length=50)),
                ('animal', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
                ('plant', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
                ('adjective2', models.CharField(max_length=50)),
            ],
        ),
    ]
