# Generated by Django 2.2 on 2023-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_sun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=50)),
                ('mythicalCreature', models.CharField(max_length=50)),
                ('adjective1', models.CharField(max_length=50)),
                ('adjective2', models.CharField(max_length=50)),
                ('adjective3', models.CharField(max_length=50)),
                ('superlative', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
            ],
        ),
    ]
