# Generated by Django 2.2 on 2023-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_haunt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective1', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('object', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
                ('animal', models.CharField(max_length=50)),
                ('plants', models.CharField(max_length=50)),
                ('adjective2', models.CharField(max_length=50)),
            ],
        ),
    ]
