# Generated by Django 2.2 on 2023-07-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_beach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('verb1', models.CharField(max_length=50)),
                ('adjective1', models.CharField(max_length=50)),
                ('noun', models.CharField(max_length=50)),
                ('adjective2', models.CharField(max_length=50)),
                ('emotion', models.CharField(max_length=50)),
                ('verb2', models.CharField(max_length=50)),
            ],
        ),
    ]
