# Generated by Django 2.2 on 2023-07-07 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_baby_breakfast_cat_closing_emergency_extra_nation_skin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='adjecitve1',
            new_name='adjective1',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='noun',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
