# Generated by Django 2.2 on 2023-07-07 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20230706_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nation',
            old_name='adjective',
            new_name='adjective1',
        ),
        migrations.RenameField(
            model_name='nation',
            old_name='noun',
            new_name='noun1',
        ),
        migrations.AddField(
            model_name='nation',
            name='noun2',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
