# Generated by Django 2.2 on 2023-07-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20230706_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='adjective3',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='jobTitle',
        ),
    ]
