# Generated by Django 2.2 on 2023-07-07 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_auto_20230706_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='adjective3',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='jobTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
